---
title: "1.Introduction to R"
author: "Md Rana Mahmud"
date: "8/15/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# শুরু 
print("Hello World")
```
```{r}
# ড্যাটা লোড করা 
data("mtcars")
```
```{r}
# প্রথম ৬ টি রো দেখা 
head(mtcars)
```
```{r}
# শেষ  ৬ টি রো দেখা 
tail(mtcars)
```
```{r}
# রো এর সংখ্যা 
nrow(mtcars)
```
```{r}
# কলাম এর সংখ্যা 
ncol(mtcars)
```
```{r}
# রো এবং কলাম এর সংখ্যা 
dim(mtcars)
```
```{r}
# সামারি স্ট্যাটিসটিক্স 
summary(mtcars)
```
```{r}
# # দিয়ে শুরু লাইন কমেন্ট 
# $ দিয়ে ভ্যারিয়েবল সিলেক্ট করা হয় 
mtcars$disp
summary(mtcars$disp)

```

```{r}

# ? দিয়ে হেল্প দেখা হয় 

?summary
```
```{r}
# কোয়ান্টাইল
quantile(mtcars$mpg, 0.45)
```
```{r}
#  রো এর নাম দেখা  
rownames(mtcars)
```

```{r}

# প্লট 
# plot
# xlab = xlabel
# ylab = ylabel
# main = Plot title
plot(mtcars$mpg, mtcars$cyl)
plot(mtcars$mpg, mtcars$cyl,
     xlab = "Milage",
     ylab = "Cylindar Size",
     main= "Milage vs Cylinader")
hist(mtcars$mpg)
```

```{r}

# প্যাকেজ ইনস্টল করা 
install.packages("ggplot2",repos = "http://cran.us.r-project.org")
# প্যাকেজ লোড করা 
library(ggplot2)
# library(abcd) কাজ করবে না 

# ggplot2 প্লট 
ggplot(mtcars, aes(mpg, wt))+geom_point()+
    theme_classic()

```

